// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Fri Dec 01 08:25:11 2017

chooser chooser_inst
(
	.clkc(clkc_sig) ,	// input  clkc_sig
	.sel(sel_sig) ,	// input  sel_sig
	.clr(clr_sig) ,	// input  clr_sig
	.outc(outc_sig) 	// output [7:0] outc_sig
);

defparam chooser_inst.S0 = 'b11111100;
defparam chooser_inst.S1 = 'b01100000;
defparam chooser_inst.S2 = 'b11011010;
defparam chooser_inst.S3 = 'b11110010;
defparam chooser_inst.S4 = 'b01100110;
defparam chooser_inst.S5 = 'b10110110;
defparam chooser_inst.S6 = 'b10111110;
defparam chooser_inst.S7 = 'b11100000;
defparam chooser_inst.S8 = 'b11111110;
defparam chooser_inst.S9 = 'b11110110;
defparam chooser_inst.S10 = 'b10011110;
defparam chooser_inst.S11 = 'b00000000;
