// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Nov 30 16:57:46 2017

frequency_divider frequency_divider_inst
(
	.clk_50mhz(clk_50mhz_sig) ,	// input  clk_50mhz_sig
	.rst(rst_sig) ,	// input  rst_sig
	.clk_1khz(clk_1khz_sig) ,	// output  clk_1khz_sig
	.clk_100hz(clk_100hz_sig) ,	// output  clk_100hz_sig
	.clk_10hz(clk_10hz_sig) ,	// output  clk_10hz_sig
	.clk_1hz(clk_1hz_sig) 	// output  clk_1hz_sig
);

defparam frequency_divider_inst.N4 = 2;
defparam frequency_divider_inst.N3 = 4;
defparam frequency_divider_inst.N2 = 8;
defparam frequency_divider_inst.N1 = 16;
