// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Fri Dec 01 10:47:03 2017

chooser chooser_inst
(
	.clkc(clkc_sig) ,	// input  clkc_sig
	.in_ms(in_ms_sig) ,	// input [7:0] in_ms_sig
	.in_s(in_s_sig) ,	// input [7:0] in_s_sig
	.in_min(in_min_sig) ,	// input [7:0] in_min_sig
	.outc(outc_sig) 	// output [3:0] outc_sig
);

defparam chooser_inst.S0 = 'b1010;
defparam chooser_inst.S1 = 'b1011;
defparam chooser_inst.S2 = 'b1100;
